### HW2_신예진

#### 1. 아래에 주어진 주석을 기반으로 하여 코딩을 해주세요.

In [1]:
import torch
import torchvision.datasets as dsets
import torchvision.transforms as transforms
import matplotlib.pylab as plt
import random

In [2]:
learning_rate = 0.1
training_epochs = 15
batch_size = 100

In [3]:
mnist_train = dsets.MNIST(root='MNIST_data/',
                         train=True,
                         transform = transforms.ToTensor(),
                         download =True)

mnist_test = dsets.MNIST(root='MNIST_data/',
                        train=False,
                        transform = transforms.ToTensor(),
                        download=True)

Extracting MNIST_data/MNIST\raw\train-images-idx3-ubyte.gz to MNIST_data/MNIST\raw


Extracting MNIST_data/MNIST\raw\train-labels-idx1-ubyte.gz to MNIST_data/MNIST\raw


Extracting MNIST_data/MNIST\raw\t10k-images-idx3-ubyte.gz to MNIST_data/MNIST\raw


Extracting MNIST_data/MNIST\raw\t10k-labels-idx1-ubyte.gz to MNIST_data/MNIST\raw
Processing...


C:\Users\Rstudio\Anaconda3\lib\site-packages\torchvision\datasets\mnist.py:469: UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at  ..\torch\csrc\utils\tensor_numpy.cpp:141.)
  return torch.from_numpy(parsed.astype(m[2], copy=False)).view(*s)



Done!




In [4]:
train_loader = torch.utils.data.DataLoader(dataset=mnist_train, 
                                          batch_size = batch_size,
                                          shuffle=True,
                                          drop_last = True)

test_loader = torch.utils.data.DataLoader(dataset=mnist_test, 
                                          batch_size = batch_size,
                                          shuffle=False,
                                          drop_last = True)

In [5]:
linear1 = torch.nn.Linear(784,100, bias=True)
linear2 = torch.nn.Linear(100,100, bias=True)
linear3 = torch.nn.Linear(100,10, bias=True)

relu = torch.nn.ReLU()
bn1 = torch.nn.BatchNorm1d(100) #number of size
bn2 = torch.nn. BatchNorm1d(100)


dropout = torch.nn.Dropout(p=0.3)

In [6]:
torch.nn.init.xavier_uniform(linear1.weight)
torch.nn.init.xavier_uniform(linear2.weight)
torch.nn.init.xavier_uniform(linear3.weight)

C:\Users\Rstudio\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: nn.init.xavier_uniform is now deprecated in favor of nn.init.xavier_uniform_.
  """Entry point for launching an IPython kernel.
C:\Users\Rstudio\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: nn.init.xavier_uniform is now deprecated in favor of nn.init.xavier_uniform_.
  
C:\Users\Rstudio\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: UserWarning: nn.init.xavier_uniform is now deprecated in favor of nn.init.xavier_uniform_.
  This is separate from the ipykernel package so we can avoid doing imports until


Parameter containing:
tensor([[-1.4327e-01, -1.0198e-01, -2.1631e-01, -5.3945e-02, -1.1043e-01,
          1.7424e-01,  1.3707e-01, -6.6992e-02, -4.6227e-02, -1.2974e-02,
         -3.6126e-02,  1.2323e-01,  2.1793e-01, -1.5587e-01,  2.0820e-01,
          1.6229e-01, -5.0635e-02,  1.4373e-01, -1.5804e-02, -1.6831e-01,
          1.5265e-01, -7.3248e-02,  1.5824e-01, -3.2106e-02,  8.2778e-02,
          6.3402e-02,  2.1614e-02,  6.9557e-02, -2.2104e-01, -1.3861e-01,
         -1.0080e-01, -7.8901e-02,  8.5597e-02, -9.7518e-02,  6.8865e-03,
         -1.4864e-01, -4.8956e-03,  1.4469e-01,  1.7819e-01, -5.2978e-02,
         -1.0098e-01, -8.2930e-02,  2.0266e-01, -1.8001e-01, -1.2747e-01,
         -8.1690e-02,  5.6006e-02, -2.2113e-02, -1.8489e-01,  9.5834e-02,
         -1.9355e-01,  2.0232e-01, -2.1460e-01, -1.0026e-01, -1.8142e-01,
         -1.8594e-01, -9.2068e-02,  1.6128e-01, -5.9895e-02,  7.6397e-02,
         -1.2061e-01, -1.2702e-01, -1.7871e-01, -4.3743e-03,  2.0347e-01,
          2.1790

In [7]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'

In [9]:
model = torch.nn.Sequential(linear1,  bn1, relu, dropout, 
                           linear2, bn2, relu,  dropout,
                            linear3).to(device)

In [10]:
criterion = torch.nn.CrossEntropyLoss().to(device)
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

In [12]:
train_total_batch  = len(train_loader)
model.train()

for epoch in range(training_epochs):
    avg_cost = 0
    
    for X,Y in train_loader:
        X= X.view(-1,28*28).to(device)
        Y= Y.to(device)
        
        optimizer.zero_grad()
        hypothesis = model(X)
        cost = criterion(hypothesis, Y)
        cost.backward()
        optimizer.step()
        
        avg_cost +=cost/ train_total_batch
    
    print('Epoch:','%04d' % (epoch+1),'cost=', '{:.9f}'.format(avg_cost))
    
print('Learning finished.')

Epoch: 0001 cost= 0.512815416
Epoch: 0002 cost= 0.381618172
Epoch: 0003 cost= 0.332564741
Epoch: 0004 cost= 0.304156423
Epoch: 0005 cost= 0.296574652
Epoch: 0006 cost= 0.289087325
Epoch: 0007 cost= 0.280850381
Epoch: 0008 cost= 0.281081885
Epoch: 0009 cost= 0.267590672
Epoch: 0010 cost= 0.267209679
Epoch: 0011 cost= 0.265150785
Epoch: 0012 cost= 0.257766902
Epoch: 0013 cost= 0.249146625
Epoch: 0014 cost= 0.242462710
Epoch: 0015 cost= 0.238580048
Learning finished.


In [14]:
with torch.no_grad():
    model.eval()
    
    X_test = mnist_test.test_data.view(-1,28*28).float().to(device)
    Y_test = mnist_test.test_labels.to(device)
    
    prediction = model(X_test)
    
    correct_prediction = torch.argmax(prediction,1)==Y_test
    accuracy = correct_prediction.float().mean()
    print('Accuracy:', accuracy.item())
    
    r = random.randint(0,len(mnist_test)-1)
    X_single_data = mnist_test.test_data[r:r+1].view(-1,28*28).float().to(device)
    Y_single_data = mnist_test.test_labels[r:r+1].to(device)
    
    print('Label: ', Y_single_data.item())
    single_prediction = model(X_single_data)
    print('Prediction: ', torch.argmax(single_prediction, 1).item())

C:\Users\Rstudio\Anaconda3\lib\site-packages\torchvision\datasets\mnist.py:60: UserWarning: test_data has been renamed data
  warnings.warn("test_data has been renamed data")
C:\Users\Rstudio\Anaconda3\lib\site-packages\torchvision\datasets\mnist.py:50: UserWarning: test_labels has been renamed targets
  warnings.warn("test_labels has been renamed targets")


Accuracy: 0.9254999756813049
Label:  4
Prediction:  4


#### 2. Layer의 hidden node 수를 증가 혹은 감소시켰을 때, train set에서의 cost와 test set에서의 Accuracy가 기존 결과와 비교하였을 때 어떻게 달라졌는지 비교

#### 784 -> 200 -> 100

In [15]:
linear4= torch.nn.Linear(784,200, bias=True)
linear5= torch.nn.Linear(200,100, bias=True)
linear6 = torch.nn.Linear(100,10, bias=True)

relu = torch.nn.ReLU()
bn3 = torch.nn.BatchNorm1d(200)
bn4 =  torch.nn.BatchNorm1d(100)
dropout = torch.nn.Dropout(p=0.3)

torch.nn.init.xavier_uniform_(linear4.weight)
torch.nn.init.xavier_uniform_(linear5.weight)
torch.nn.init.xavier_uniform_(linear6.weight)

Parameter containing:
tensor([[-0.1568,  0.0559, -0.1477, -0.1963, -0.1895,  0.2295,  0.1548,  0.1275,
         -0.0152, -0.1530,  0.0960,  0.1581,  0.1658,  0.0917,  0.1718, -0.0548,
          0.0048, -0.1054,  0.0206,  0.0599, -0.1970, -0.1890,  0.0432,  0.2218,
          0.0488,  0.1208, -0.1950, -0.0136,  0.1183, -0.0832,  0.2099, -0.0098,
         -0.2243,  0.1976, -0.0441, -0.0775,  0.1811, -0.1543, -0.1315,  0.2062,
         -0.1905,  0.0354, -0.1678, -0.1398, -0.1353, -0.1014,  0.0170,  0.1560,
          0.1909,  0.2211, -0.1806, -0.1392, -0.1733, -0.0152, -0.0197, -0.0351,
          0.1811, -0.0211,  0.1278,  0.1197,  0.0897, -0.0974, -0.0454, -0.1297,
         -0.1507, -0.0453, -0.0786,  0.1355, -0.0597, -0.2161, -0.2025,  0.0186,
         -0.1721, -0.0139,  0.2284,  0.1528, -0.0136, -0.1459,  0.1721,  0.0652,
         -0.2142, -0.2177,  0.1755, -0.1122, -0.0700,  0.0719, -0.0529, -0.1182,
         -0.1994,  0.1758, -0.0755, -0.0522, -0.1932, -0.0667, -0.1134, -0.2245,
      

In [16]:
model_1= torch.nn.Sequential(linear4,bn3,relu,dropout,linear5,bn4, relu,dropout,linear6).to(device)

In [17]:
criterion = torch.nn.CrossEntropyLoss().to(device)
optimizer = torch.optim.Adam(model_1.parameters(),lr=learning_rate)
train_total_batch = len(train_loader)

In [18]:
model_1.train()

for epoch in range(training_epochs):
    avg_cost = 0

    for X,Y in train_loader:
        X = X.view(-1, 28*28).to(device)
        Y = Y.to(device)
        
        optimizer.zero_grad()
        hypothesis = model_1(X)
        cost = criterion(hypothesis, Y)
        cost.backward()
        optimizer.step()
        avg_cost += cost/ train_total_batch
    
    print('Epoch:','%04d' % (epoch+1),'cost=', '{:.9f}'.format(avg_cost))

print('Learning finished.')

Epoch: 0001 cost= 0.454125047
Epoch: 0002 cost= 0.328139603
Epoch: 0003 cost= 0.288275033
Epoch: 0004 cost= 0.266167164
Epoch: 0005 cost= 0.248139113
Epoch: 0006 cost= 0.250120431
Epoch: 0007 cost= 0.233583078
Epoch: 0008 cost= 0.229012609
Epoch: 0009 cost= 0.218645975
Epoch: 0010 cost= 0.220448241
Epoch: 0011 cost= 0.219343126
Epoch: 0012 cost= 0.205362886
Epoch: 0013 cost= 0.211231396
Epoch: 0014 cost= 0.202726185
Epoch: 0015 cost= 0.183361217
Learning finished.


In [19]:
with torch.no_grad():
    model_1.eval()
    
    X_test = mnist_test.test_data.view(-1,28*28).float().to(device)
    Y_test = mnist_test.test_labels.to(device)
    
    prediction = model_1(X_test)
        
    correct_prediction = torch.argmax(prediction,1)==Y_test
    accuracy = correct_prediction.float().mean() 
    print('Accuracy:', accuracy.item()) 
    
    r = random.randint(0,len(mnist_test)-1)
    X_single_data = mnist_test.test_data[r:r+1].view(-1,28*28).float().to(device)
    Y_single_data = mnist_test.test_labels[r:r+1].to(device)
    
    print('Label: ', Y_single_data.item())
    single_prediction = model_1(X_single_data)
    print('Prediction: ', torch.argmax(single_prediction, 1).item())

Accuracy: 0.9404000043869019
Label:  8
Prediction:  0


##### 784->150->50

In [20]:
linear7= torch.nn.Linear(784,150, bias=True)
linear8= torch.nn.Linear(150,50, bias=True)
linear9 = torch.nn.Linear(50,10, bias=True)

relu = torch.nn.ReLU()
bn5 = torch.nn.BatchNorm1d(150)
bn6 =  torch.nn.BatchNorm1d(50)

dropout = torch.nn.Dropout(p=0.3)

torch.nn.init.xavier_uniform_(linear7.weight)
torch.nn.init.xavier_uniform_(linear8.weight)
torch.nn.init.xavier_uniform_(linear9.weight)

Parameter containing:
tensor([[ 1.7485e-01, -2.0509e-01,  1.0968e-01, -2.4953e-02, -1.9736e-01,
          1.5979e-01, -1.2590e-01,  8.8654e-03,  9.7382e-02,  1.3839e-01,
         -3.0570e-01,  8.0246e-02, -3.1390e-01, -2.8424e-01, -9.8025e-02,
          2.4052e-02, -1.7239e-01, -1.7766e-01, -4.8179e-02, -1.2388e-01,
         -1.4764e-01, -1.6261e-01, -3.0202e-01,  1.4000e-01, -1.7158e-01,
          1.9509e-01,  3.2688e-02,  3.0909e-01,  1.4583e-01, -4.5996e-02,
          2.3496e-01,  1.3800e-01, -2.0479e-01, -1.8202e-01,  2.5202e-01,
         -1.2104e-01,  1.2390e-01,  1.3205e-01, -2.6791e-01, -2.5703e-01,
          2.8499e-01, -1.4580e-01, -2.9219e-01, -1.2449e-01, -2.1938e-01,
         -2.6892e-02, -3.0421e-01, -3.0995e-01,  3.0628e-02,  1.2769e-01],
        [-9.4942e-03,  5.8623e-02, -2.1349e-01, -9.0995e-02, -6.9170e-03,
         -1.0219e-01,  2.8444e-01, -1.4533e-01, -2.8501e-01,  1.4398e-01,
          2.9918e-01, -2.6231e-03, -2.8151e-01,  4.3534e-02, -2.3266e-01,
          5.522

In [21]:
model_2= torch.nn.Sequential(linear7,bn5,relu,dropout,linear8,bn6, relu,dropout,linear9).to(device)

criterion = torch.nn.CrossEntropyLoss().to(device)
optimizer = torch.optim.Adam(model_2.parameters(),lr=learning_rate)
train_total_batch = len(train_loader)

In [22]:
model_2.train()

for epoch in range(training_epochs):
    avg_cost = 0

    for X,Y in train_loader:
        X = X.view(-1, 28*28).to(device)
        Y = Y.to(device)
        
        optimizer.zero_grad()
        hypothesis = model_2(X)
        cost = criterion(hypothesis, Y)
        cost.backward()
        optimizer.step()
        avg_cost += cost/ train_total_batch
    
    print('Epoch:','%04d' % (epoch+1),'cost=', '{:.9f}'.format(avg_cost))

print('Learning finished.')

Epoch: 0001 cost= 0.481632590
Epoch: 0002 cost= 0.332700282
Epoch: 0003 cost= 0.304669112
Epoch: 0004 cost= 0.286051154
Epoch: 0005 cost= 0.260747403
Epoch: 0006 cost= 0.260704279
Epoch: 0007 cost= 0.257174045
Epoch: 0008 cost= 0.244761392
Epoch: 0009 cost= 0.239918828
Epoch: 0010 cost= 0.223045096
Epoch: 0011 cost= 0.222738445
Epoch: 0012 cost= 0.216413900
Epoch: 0013 cost= 0.215562791
Epoch: 0014 cost= 0.218311787
Epoch: 0015 cost= 0.210391760
Learning finished.


In [23]:
with torch.no_grad():
    model_2.eval()
    
    X_test = mnist_test.test_data.view(-1,28*28).float().to(device)
    Y_test = mnist_test.test_labels.to(device)
    
    prediction = model(X_test)
    
    correct_prediction = torch.argmax(prediction,1)==Y_test
    accuracy = correct_prediction.float().mean()
    print('Accuracy:', accuracy.item())
    
    r = random.randint(0,len(mnist_test)-1)
    X_single_data = mnist_test.test_data[r:r+1].view(-1,28*28).float().to(device)
    Y_single_data = mnist_test.test_labels[r:r+1].to(device)
    
    print('Label: ', Y_single_data.item())
    single_prediction = model_2(X_single_data)
    print('Prediction: ', torch.argmax(single_prediction, 1).item())

Accuracy: 0.9254999756813049
Label:  3
Prediction:  3
